# Generated by Django 3.1.3 on 2020-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reading_status',
            field=models.CharField(choices=[(0, 'acquired'), (1, 'started'), (2, 'read')], default='acquired', max_length=36),
        ),
    ]
