# Generated by Django 3.1.3 on 2020-11-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20201124_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reading_status',
            field=models.CharField(max_length=36),
        ),
    ]
